package model.Enums;

public enum GameEvent {

    NORMAL,
    CHAIN,
    ACTIVATE_TRAP,
    SACRIFICE_FOR_SUMMON_SET,
    ASK_FOR_CONFIRMATION_FOR_ACTIVATE_ANOTHER_SPELL,
    ASK_FOR_CONFIRMATION_FOR_CHAIN,
    ASK_FOR_ACTIVATE_TRAP,
    ASK_FOR_SIDE_DECK,
    MAN_EATER_BUG
}
